name: Pull and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image
        run: docker pull original/imagename

      - name: Tag Docker image
        run: docker tag original/imagename yourusername/yourrepository:tag

      - name: Push Docker image
        run: docker push yourusername/yourrepository:tag
